# Changes the header of the page to reflect the data source.
title: Nigeria MDG Information System (NMIS)
id: nmis_ui_data_2ef92c15

# If we set "versions" for the data, we can use "version bumps" to force new loading
# of the data.
# (Experimental. Not yet implemented.)
version: 1

# Ideally, we don't want to tie ourselves to States + LGAs,
# This is not currently used, but in the future, will allow the
# UI to continue to display "State"/"LGA"
groupings: {group: State, local: LGA}

# Relative path to a file with a list of States and LGAs.
# -> See districts.yaml for more info

# when a district cannot load a data module, it falls back on these defaults
defaults:
  presentation/sectors:
    - presentation/sectors.json
  variables/variables:
    - variables/variables.json
  geo/districts:
    - geo/districts.json
  presentation/facilities:
    - presentation/facilities.json